name: ci

on: push

jobs:
  checkout:
    name: checkout repo
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
  test:
    name: test
    runs-on: ubuntu-18.04
    needs: checkout
    steps:
      - name: Run linter
        run: make lint
